// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEL3TLvxgnRxG43oy8wiVTjt8cZawhqTA',
    appId: '1:569428615506:web:980afe79c15fa4e6485a8b',
    messagingSenderId: '569428615506',
    projectId: 'klyroo',
    authDomain: 'klyroo.firebaseapp.com',
    storageBucket: 'klyroo.firebasestorage.app',
    measurementId: 'G-H1R52HVC7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu-HBIzCHHcez6u90VXqluhWfaOCo1EMY',
    appId: '1:569428615506:android:218d3727fb6221ba485a8b',
    messagingSenderId: '569428615506',
    projectId: 'klyroo',
    storageBucket: 'klyroo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8iyZ6n8JNdvD_6-lwep7NOo0sdOj6h00',
    appId: '1:569428615506:ios:03df42adeb8081c5485a8b',
    messagingSenderId: '569428615506',
    projectId: 'klyroo',
    storageBucket: 'klyroo.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );
}
